<a href="https://colab.research.google.com/github/tnagata/Deep-learning-with-Python/blob/master/1_making_sure_things_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch


In [6]:
torch.version.__version__

'1.6.0+cu101'

In [7]:
a = torch.ones(3,3)

In [8]:
b = torch.ones(3,3)

In [9]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [14]:
a = a.to('cuda')
print(a)
b = b.to('cuda')
a + 2*b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], device='cuda:0')